-- USERS
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U1','Paul','paul01@gmail.com','IT Billing')
;
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U2','Allen','texas@imfblog.org','Engineering')
;
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U3','Teddy','norway@iotm.com','IT Billing')
;
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U4','Paul','paul_p@naver.com','Developer')
;

-- AuthNames
INSERT INTO auth_names(AUTH_NAME,UNIQUE_ID)
VALUES ('GUEST','B1')
;
INSERT INTO auth_names(AUTH_NAME,UNIQUE_ID)
VALUES ('ADMIN','B2')
;
INSERT INTO auth_names(AUTH_NAME,UNIQUE_ID)
VALUES ('MANAGER','B3')
;

-- auths
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U1','B1')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U1','B2')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U2','B1')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U2','B2')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U2','B3')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U3','B1')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U4','B2')
;
INSERT INTO auths(UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U4','B1')
;



-- 회원탈퇴
DELETE FROM users 
WHERE UNIQUE_ID = 'U2'
;

DELETE FROM users 
WHERE UNIQUE_ID = 'U4'
;

DELETE FROM auths
WHERE UNIQUE_ID_AUTH_NAMES = 'U2'
;

DELETE FROM auths
WHERE UNIQUE_ID_AUTH_NAMES = 'U4'
;

SELECT *
FROM users 
;

SELECT *
FROM auth_names
;

SELECT *
FROM auths
;